language: cpp
os: linux
dist: bionic

addons:
  apt:
    sources:
      # Official Kitware APT repository. Currently supports Bionic and Xenial.
      # More information at: https://apt.kitware.com
      - sourceline: "deb https://apt.kitware.com/ubuntu/ xenial main"
        key_url: "https://apt.kitware.com/keys/kitware-archive-latest.asc"
    packages:
      - cmake

script:
  - cmake -P cmakepp.cmake test_execute_glob_parallel --recurse --no-status tests/**.cmake

after_success: "cmake -P build/after_success.cmake"
after_failure: "cmake -P build/after_failure.cmake"
after_script: "cmake -P build/after_script.cmake"
branches:
  only:
    - master
    - dev
