name: CI
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
jobs:
  test:
    name: Testing on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]

    steps:
      - uses: actions/checkout@v1

      - uses: lukka/get-cmake@latest

      - run: git config --global user.email "Test@AnotherFoxGuy.com"
      - run: git config --global user.name "Test"

      - name: Configure
        run: cmake -DFAST_TESTS=ON .

      - name: Run all test
        run: ctest -C Release
        env:
          CTEST_OUTPUT_ON_FAILURE: 1

      - name: Build
        run: cmake --build . --target compile
